M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date Yaw 29 F-Ɛ 2022 18:09:08
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-29T18:09:08+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
%
G90
G05
T1
X4.2898Y-3.8122
T0
M30
